

drop table ev_models cascade constraints purge;
drop table ev_sightings cascade constraints purge;
drop table ev_locations cascade constraints purge;

drop table states cascade constraints purge;
drop table counties cascade constraints purge;
drop table cities cascade constraints purge;


--========================================
--== ev_models
--========================================

create table ev_models (
	make varchar2(30) not null,
	model varchar2(30) not null,
	constraint ev_models_pk primary key (make, model)
)
--organization index
/

--========================================
--== states
--========================================

create table states (
	abbreviation varchar2(2),
	name varchar2(30) not null,
	constraint states_pk primary key(abbreviation)
)
--organization index
/

create unique index states_name on states(name);


--========================================
--== counties
--========================================

create table counties (
	county varchar2(30) not null,
	state varchar2(2) not null,
	constraint counties_pk primary key(county,state)
)
--organization index
/

create index counties_state_idx on counties(state,county);

alter table counties add constraint counties_state_fk foreign key (state) references states(abbreviation);

--========================================
--== cities
--========================================

create table cities (
	city varchar2(30) not null,
	county varchar2(30) not null,
	state varchar2(2) not null,
	constraint cities_pk primary key(city,county,state)
)
--organization index
/

create index cities_co_st_idx on cities(county,state);

alter table cities add constraint cities_co_st_fk foreign key(county,state) references counties(county,state);


--========================================
--== ev_locations
--== dummy lookup table
--========================================

create table ev_locations(
	make varchar2(30) not null,
	model varchar2(30) not null,
	city varchar2(30) not null,
	county varchar2(30) not null,
	state varchar2(2) not null,
	constraint ev_locations_pk primary key(make, model, city, county, state)
)
/


--========================================
--== ev_sightings
--========================================

create table ev_sightings (
	id number generated by default on null as identity,
	make varchar2(30) not null,
	model varchar2(30) not null,
	city varchar2(30) not null,
	county varchar2(30) not null,
	state varchar2(2) not null,
	date_sighted date not null,
	constraint ev_sightings_pk primary key(id)
)
/

create index evs_city_co_st_idx on ev_sightings(city,county,state);
alter table ev_sightings add constraint evs_city_co_st_fk foreign key(city,county,state)  references cities(city,county,state);

create index evs_make_model_idx on ev_sightings(make, model);
alter table ev_sightings add constraint evs_make_model_fk foreign key(make, model)  references ev_models(make, model);




