set echo on
spool _chair_tab.log

drop table jkstill.chair cascade constraints purge;

--########################################
--## TABLE DDL
--########################################

  CREATE TABLE JKSTILL.CHAIR
   (	CHAIR NUMBER(10,0),
	NAME CHAR(15 CHAR),
	DESCRIPTION CHAR(63 CHAR),
	CLINIC NUMBER(10,0),
	"ROW" NUMBER(5,0),
	COL NUMBER(5,0),
	UNAVAILABLE NUMBER(5,0),
	IMPORT CHAR(10 CHAR),
	LOCATION CHAR(6 CHAR),
	BLOCKSIZE NUMBER(5,0),
	ISOVERFLOW NUMBER(5,0),
	OVERFLOWORDER NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

  CREATE UNIQUE INDEX JKSTILL.CHAIR_PRIMARY ON JKSTILL.CHAIR (CHAIR)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
--ALTER TABLE JKSTILL.CHAIR ADD CONSTRAINT CHAIR_PRIMARY PRIMARY KEY (CHAIR)
  --USING INDEX JKSTILL.CHAIR_PRIMARY  ENABLE;

--########################################
--## INDEX DDL
--########################################


  CREATE INDEX JKSTILL.CHAIR_CLINIC ON JKSTILL.CHAIR (CLINIC, UNAVAILABLE, CHAIR, NAME)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


  CREATE UNIQUE INDEX JKSTILL.CHAIR_PRIMARY ON JKSTILL.CHAIR (CHAIR)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


  CREATE INDEX JKSTILL.CHAIR_NAME ON JKSTILL.CHAIR (NAME)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


  CREATE INDEX JKSTILL.CHAIR_IMPORT ON JKSTILL.CHAIR (IMPORT)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

spool off
set echo off
