set echo on
spool _holiday_tab.log




drop table jkstill.holiday cascade constraints purge;

  CREATE TABLE JKSTILL.HOLIDAY
   (	ID NUMBER(10,0),
	CLINIC NUMBER(10,0),
	DESCRIPTION CHAR(30 CHAR),
	STARTDATE DATE,
	ENDDATE DATE,
	PARTIALDAY NUMBER(5,0),
	STARTTIME NUMBER(10,0),
	ENDTIME NUMBER(10,0),
	DISPLAYDESC VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
 
  CREATE UNIQUE INDEX JKSTILL.HOLIDAY_PRIMARY ON JKSTILL.HOLIDAY (ID)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
--ALTER TABLE JKSTILL.HOLIDAY ADD CONSTRAINT HOLIDAY_PRIMARY PRIMARY KEY (ID)
  --USING INDEX JKSTILL.HOLIDAY_PRIMARY  ENABLE;

--########################################
--## INDEX DDL
--########################################


  CREATE UNIQUE INDEX JKSTILL.HOLIDAY_PRIMARY ON JKSTILL.HOLIDAY (ID)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


  CREATE INDEX JKSTILL.HOLIDAY_CLINIC ON JKSTILL.HOLIDAY (CLINIC, STARTDATE)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1m NEXT 1m MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

spool off
set echo off
